server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul
zuul:
  routes:
    api-user:
      path: /user/**
      url: http://localhost:1111/user
    api-movie:
      path: /movie/**
      url: http://localhost:2222/movie